import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import LeftSidebar from "@/components/globals/left-sidebar";
import Header from "@/components/globals/header";
import ReduxProvider from "@/app/ReduxProvider";
import { TransitionProvider } from "./context/TransitionContext";
import Overlay from "@/components/globals/Overlay";
import Footer from "@/components/globals/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} flex flex-col bg-slate-900 text-white/50 min-h-screen`}>
                <TransitionProvider>
                    <ReduxProvider>
                        <Header />
                        <div className="relative top-0 left-0 flex flex-col w-full z-auto">
                            <Overlay />
                            <div className="block relative">
                                {children}
                            </div>
                        </div>
                        <Footer />
                    </ReduxProvider>
                </TransitionProvider>
            </body>
        </html>
    );
}
