import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import LeftSidebar from "@/components/globals/left-sidebar";
import Header from "@/components/globals/header";
import ReduxProvider from "@/app/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-slate-900 text-white/50`}>
                <ReduxProvider>
                    <Header />
                    <div className="relative">
                        <div className="relative container z-10">
                            {children}
                        </div>
                    </div>
                </ReduxProvider>
            </body>
        </html>
    );
}
